ALTER TABLE EXPENSE ADD COLUMN BUDGET_ID BIGINT,
ADD CONSTRAINT FK_BUDGET_EXPENSE FOREIGN KEY (BUDGET_ID) REFERENCES BUDGET(ID);

ALTER TABLE INCOME ADD COLUMN BUDGET_ID BIGINT,
ADD CONSTRAINT FK_BUDGET_INCOME FOREIGN KEY (BUDGET_ID) REFERENCES BUDGET(ID);

ALTER TABLE BUDGET DROP COLUMN TOTAL_SPENT, DROP COLUMN TOTAL_REMAINING;
ALTER TABLE BUDGET_CATEGORY DROP COLUMN SPENT_VALUE, DROP COLUMN REMAINING_VALUE;


